#include <iostream>
using namespace std;

 cout<<"stable vs unstable sorting algorithm\n";
// A sorting algorithm is said to be stable if it preserves the relative order of equal elements in the sorted output. In other words, if two elements are equal, they will appear in the same order in the sorted output as they do in the input. On the other hand, an unstable sorting algorithm does not guarantee the preservation of the relative order of equal elements.
//linear search--> stable--> because it only compares each element with the key and does not change the order of equal elements.
//binary search--> stable--> because it only works on sorted arrays, and the relative order of equal elements is preserved in a sorted array.
//bubble sort--> stable--> example if we have an array [5, 1, 4, 2, 8] and we want to sort it in ascending order, after the first pass of bubble sort, the array will be [1, 4, 2, 5, 8]. Here, the relative order of the equal elements (5 and 5) is preserved. In contrast, if we use selection sort to sort the same array, the relative order of the equal elements will not be preserved. After the first pass of selection sort, the array will be [1, 5, 4, 2, 8], and the relative order of the equal elements (5 and 5) will not be preserved.
//insertion sort--> stable---> example if we have an array [5, 1, 4, 2, 8] and we want to sort it in ascending order, after the first pass of insertion sort, the array will be [1, 5, 4, 2, 8]. Here, the relative order of the equal elements (5 and 5) is preserved. In contrast, if we use selection sort to sort the same array, the relative order of the equal elements will not be preserved. After the first pass of selection sort, the array will be [1, 5, 4, 2, 8], and the relative order of the equal elements (5 and 5) will not be preserved.
//selection sort--> unstable--> example if we have an array [5, 1, 4, 2, 8] and we want to sort it in ascending order, after the first pass of selection sort, the array will be [1, 5, 4, 2, 8]. Here, the relative order of the equal elements (5 and 5) is not preserved. In contrast, if we use bubble sort to sort the same array, the relative order of the equal elements will be preserved. After the first pass of bubble sort, the array will be [1, 4, 2, 5, 8], and the relative order of the equal elements (5 and 5) will be preserved.
//merge sort--> stable-->example if [5, 1, 4, 2, 8] and we want to sort in ascending order, after the first pass of merge sort, the array will be [1, 2, 4, 5, 8]. Here, the relative order of the equal elements (5 and 5) is preserved. In contrast, if we use quick sort to sort the same array, the relative order of the equal elements will not be preserved. After the first pass of quick sort, the array will be [1, 2, 4, 5, 8], and the relative order of the equal elements (5 and 5) will not be preserved.
//quick sort--> unstable-->example if[5, 1, 4, 2, 8] and we want to sort in ascending order, after the first pass of quicksort, the array will be [1, 2, 4, 5, 8]. Here, the relative order of the equal elements (5 and 5) is not preserved. In contrast, if we use merge sort to sort the same array, the relative order of the equal elements will be preserved. After the first pass of merge sort, the array will be [1, 2, 4, 5, 8], and the relative order of the equal elements (5 and 5) will be preserved.